//文章列表
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_ARTICLE_LIST_FAILURE = 'GET_ARTICLE_LIST_FAILURE'

export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'
//文章
export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE'
export const CLEAR_ARTICLE = 'CLEAR_ARTICLE'
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE'
